version: "3"
services:
  parent:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ["multivisor", "-c", "/etc/multivisor.conf"]
    ports:
      - 22000:22000
  personid:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ["supervisord", "-c", "/etc/supervisord/personid.conf"]
    ports:
      - 9011:9011
