[inet_http_server]
port=:9011

[supervisord]
identifier=lid001
nodaemon = true
pidfile = /var/run/supervisord.pid
logfile = /var/log/supervisord/supervisord.log
childlogdir = /var/log/supervisord
logfile_backups=10
logfile_maxbytes=1MB

[supervisorctl]
serverurl=http://localhost:9001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[eventlistener:multivisor-rpc]
command=multivisor-rpc
events=PROCESS_STATE,SUPERVISOR_STATE_CHANGE

[group:personid]
programs=client-update,onezero,spread-watcher

[program:multivisor]
command=multivisor -c /etc/multivisor.conf
autorestart=unexpected
stdout_logfile=%(program_name)s.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=10
stderr_logfile=%(program_name)s.err.log
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=1


[program:client-update]
process_name=%(program_name)s
command=/usr/bin/php /var/www/riskv3/account/artisan service:client-update --debug
autostart=true
autorestart=true
user=go
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/riskv3/account/storage/logs/service-client-update.log

[program:spread-watcher]
process_name=%(program_name)s
command=/usr/bin/php /var/www/riskv3/system/artisan spread:watcher --server=MT5DEVRF --logins="2098889338,2098889339" --driver=Surya
;command=/usr/bin/php /var/www/riskv3/system/artisan spread:watcher --server=MT4DEV --logins=2007968932 --driver=Surya
;command=/usr/bin/php /var/www/riskv3/system/artisan spread:watcher --server=MT5DEVRF --logins=2098889339 --driver=Surya --debug --write-log
;command=/usr/bin/php /var/www/riskv3/system/artisan spread:watcher --server=MT5DEMORF --logins=1021,1049 --driver=Surya --write-log
;command=/usr/bin/php /var/www/riskv3/system/artisan spread:watcher --server=MT4DEV --login=95536148 --driver=Surya --write-log
;command=/usr/bin/php /var/www/riskv3/system/artisan spread:watcher --server=MT4DEV --login=92715090 --driver=Surya --write-log
autostart=true
autorestart=true
user=go
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/riskv3/system/storage/logs/spread-watcher.log
