[inet_http_server]
port=:9041

[supervisord]
identifier=personid-v2

[supervisorctl]
serverurl=http://localhost:9041

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[rpcinterface:multivisor]
supervisor.rpcinterface_factory = multivisor.rpc:make_rpc_interface
bind=*:9042

[group:personid-v2]
programs=client-update-v2,spread-watcher-v2

[program:client-update-v2]
process_name=%(program_name)s
command=/usr/bin/php /var/www/riskv3/account/artisan service:client-update --debug
autostart=true
autorestart=true
user=go
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/riskv3/account/storage/logs/service-client-update.log

[program:spread-watcher-v2]
process_name=%(program_name)s
command=/usr/bin/php /var/www/riskv3/system/artisan spread:watcher --server=MT5DEVRF --logins="2098889338,2098889339" --driver=Surya
;command=/usr/bin/php /var/www/riskv3/system/artisan spread:watcher --server=MT4DEV --logins=2007968932 --driver=Surya
;command=/usr/bin/php /var/www/riskv3/system/artisan spread:watcher --server=MT5DEVRF --logins=2098889339 --driver=Surya --debug --write-log
;command=/usr/bin/php /var/www/riskv3/system/artisan spread:watcher --server=MT5DEMORF --logins=1021,1049 --driver=Surya --write-log
;command=/usr/bin/php /var/www/riskv3/system/artisan spread:watcher --server=MT4DEV --login=95536148 --driver=Surya --write-log
;command=/usr/bin/php /var/www/riskv3/system/artisan spread:watcher --server=MT4DEV --login=92715090 --driver=Surya --write-log
autostart=true
autorestart=true
user=go
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/riskv3/system/storage/logs/spread-watcher.log
